name: Deploy Windows Server 2022 VM

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Deploy ARM template
      run: |
        az deployment group create \
          --name "vm-deployment" \
          --resource-group <your-resource-group-name> \
          --template-file windows-server-2022-vm.json \
          --parameters \
            vmName=<vm-name> \
            adminUsername=<admin-username> \
            adminPassword='${{ secrets.ADMIN_PASSWORD }}' \
            vmSize=<vm-size> \
            osDiskType=<os-disk-type> \
          --location <azure-region>
