name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace }}

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
    # Checkout code from the repository
    - name: Checkout repository
      uses: actions/checkout@v1

    # List files in the IaC\AzCLI directory (optional step)
    - name: Look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'

    # Provision virtual machine in Azure
    - name: Provision virtual machine in Azure
      env:
        RESOURCE_GROUP: MyResourceGroup  # Replace with your resource group name
        RESOURCE_GROUP_REGION: centralindia  # Replace with your resource group region
        SERVER_NAME: githubactions  # Replace with your desired server name
        ADMIN_LOGIN: riyanshj83@gmail.com  # Replace with your admin login

      run: |
        powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'" `
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }} `
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} `
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} `
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }} `
        -resourceGroupName $env:RESOURCE_GROUP `
        -resourceGroupNameRegion $env:RESOURCE_GROUP_REGION `
        -serverName $env:SERVER_NAME `
        -adminLogin $env:ADMIN_LOGIN `
        -adminPassword ${{ secrets.ADMIN_PASSWORD }}
